set nocompatible

" automatically install vim-plug if it does not exist
if empty(glob('~/.config/vim/autoload/plug.vim'))
  silent !curl -fLo ~/.config/vim/autoload/plug.vim --create-dirs
  \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" initialize vim plugins using vim-plug
call plug#begin('~/.config/vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'christoomey/vim-tmux-navigator'
Plug 'easymotion/vim-easymotion'
Plug 'itchyny/lightline.vim'
Plug 'jonlai/smyth'
Plug 'junegunn/fzf.vim'
Plug 'mengelbrecht/lightline-bufferline'
Plug 'sheerun/vim-polyglot'
Plug 'tomtom/tcomment_vim'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-sleuth'

call plug#end()

" general settings
syntax enable
set ruler
set showcmd
set showmatch
set nowrap
set nofoldenable
set hidden
set hlsearch
set incsearch
set wildmenu
set updatetime=500
set colorcolumn=81,101
set clipboard=unnamed
set viminfo+=n~/.config/vim/viminfo

" indentation
set shiftround
set expandtab
set autoindent
set backspace=indent,eol,start

" line numbering
set number
set relativenumber
set cursorline
set cursorlineopt=number
autocmd InsertEnter,InsertLeave * :set invrelativenumber

" mappings
let mapleader=' '
nnoremap Q <nop>
nnoremap q: <nop>
nnoremap n nzz
nnoremap N Nzz
nnoremap <leader>p :set invpaste<cr>
nnoremap <leader>q :bd<cr>
nnoremap <leader>n :echo synIDattr(synID(line('.'), col('.'), 1), 'name')<cr>
nnoremap <expr> <leader>h (&hls && v:hlsearch ? ':noh' : ':set hls').'<cr>'
nnoremap <c-j> :bp<cr>
nnoremap <c-k> :bn<cr>
inoremap <c-j> <esc>:bp<cr>
inoremap <c-k> <esc>:bn<cr>
vnoremap <c-j> <esc>:bp<cr>
vnoremap <c-k> <esc>:bn<cr>

" jonlai/smyth.vim
if exists('+termguicolors')
  let &t_8f = "\<esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<esc>[48;2;%lu;%lu;%lum"
  set termguicolors
endif
colorscheme smyth

" easymotion/vim-easymotion
map <leader> <plug>(easymotion-prefix)

" tomtom/tcomment_vim
let g:tcomment_maps = 0
nnoremap <silent> <leader>x :TComment<cr>
vnoremap <silent> <leader>x :TComment<cr>

" junegunn/fzf.vim
set rtp+=~/.local/bin
cnoreabbrev fzf FZF
nnoremap <silent> <leader>l :Lines<cr>
nnoremap <silent> <leader>d :GFiles<cr>
nnoremap <silent> <leader>c :BCommits<cr>

" christoomey/vim-tmux-navigator
let g:tmux_navigator_no_mappings = 1
nmap <c-@> <c-space>
imap <c-@> <c-space>
nnoremap <silent> <c-space>h :TmuxNavigateLeft<cr>
nnoremap <silent> <c-space>j :TmuxNavigateDown<cr>
nnoremap <silent> <c-space>k :TmuxNavigateUp<cr>
nnoremap <silent> <c-space>l :TmuxNavigateRight<cr>
nnoremap <silent> <c-space>x <c-w>q
inoremap <silent> <c-space>h <c-o>:TmuxNavigateLeft<cr>
inoremap <silent> <c-space>j <c-o>:TmuxNavigateDown<cr>
inoremap <silent> <c-space>k <c-o>:TmuxNavigateUp<cr>
inoremap <silent> <c-space>l <c-o>:TmuxNavigateRight<cr>
inoremap <silent> <c-space>x <esc><c-w>q

" sheerun/vim-polyglot
let g:javascript_plugin_jsdoc = 1

" airblade/vim-gitgutter
let g:gitgutter_map_keys = 0
let g:gitgutter_sign_priority = 5

" mengelbrecht/lightline-bufferline
set showtabline=2
let g:lightline#bufferline#filename_modifier = ':~:.'
let g:lightline#bufferline#modified = '✱'
let g:lightline#bufferline#read_only = ''
let g:netrw_fastbrowse = 0
autocmd FileType netrw setl bufhidden=wipe

" itchyny/lightline.vim
set noshowmode
set timeoutlen=1000
set ttimeoutlen=0
set laststatus=2
let g:lightline = {
\ 'active': {
\   'left': [
\     ['mode', 'paste'],
\     ['readonly', 'fugitive', 'modified'],
\   ],
\   'right': [['lineinfo'], ['percent'], ['fileformat', 'filetype']],
\ },
\ 'colorscheme': 'smyth',
\ 'component': {
\   'fileformat': '%{winwidth(0) > 70 ? &fileformat : ""}',
\   'lineinfo': "\u2632 %3l:%-2v",
\   'readonly': '%{&ft !~? "help" && &readonly ? "\xf0\x9f\x94\x92" : ""}'
\ },
\ 'component_expand': { 'buffers': 'lightline#bufferline#buffers' },
\ 'component_function': {
\   'fugitive': 'LightlineFugitive',
\ },
\ 'component_type': { 'buffers': 'tabsel' },
\ 'component_visible_condition': { 'fileformat': 'winwidth(0) > 70' },
\ 'tabline': { 'left': [['buffers']], 'right': [['fileencoding']] },
\ 'tabline_subseparator': { 'left': '', 'right': '' },
\}

" displays current git branch in lightline using vim-fugitive
fu! LightlineFugitive()
  if !exists('*FugitiveHead') | return '' | endif
  let l:branch = FugitiveHead()
  return l:branch !=# '' ? "\u16A0 " . l:branch : ''
endfu

" turn off syntax and language servers if buffer is large
fu! IsLargeBuffer()
  if line2byte(line("$") + 1) < 1000000 | return | endif
  syntax clear
endfu
autocmd BufWinEnter * call IsLargeBuffer()

" strip whitespace while preserving cursor position, for all non-markdown files
fu! StripTrailingWhitespace()
  if &ft =~ 'markdown' | return | endif
  let l:l = line('.')
  let l:c = col('.')
  %s/\s\+$//e
  call cursor(l:l, l:c)
endfu
autocmd BufWritePre * call StripTrailingWhitespace()
